### PR TITLE
Revert "sync with upstream"

### PR DESCRIPTION
**Pull request by pmoust**
Reverts PeoplePerHour/terraform#10 due  to https://github.com/hashicorp/terraform/issues/1047

Graph generation has issues, just started the CI on Shippable and got a plan change on 'test'
```
~ aws_elb.pph_sandboxapi_elb
    instances.#: "" => "<computed>"

~ aws_elb.pph_sandboxseagrave_elb
    instances.#: "" => "<computed>"

~ aws_elb.pph_sandboxweb_elb
    instances.#: "" => "<computed>"

+ aws_instance.pph_sandbox
    ami:                                       "" => "ami-02f8b16a"
    associate_public_ip_address:               "" => "1"
    availability_zone:                         "" => "us-east-1b"
    block_device.#:                            "" => "<computed>"
    instance_type:                             "" => "m3.medium"
    key_name:                                  "" => "<computed>"
    private_dns:                               "" => "<computed>"
    private_ip:                                "" => "<computed>"
    public_dns:                                "" => "<computed>"
    public_ip:                                 "" => "<computed>"
    root_block_device.#:                       "" => "1"
    root_block_device.0.delete_on_termination: "" => "1"
    root_block_device.0.device_name:           "" => "/dev/sda1"
    root_block_device.0.volume_size:           "" => "128"
    root_block_device.0.volume_type:           "" => "gp2"
    security_groups.#:                         "" => "5"
    security_groups.1610004074:                "" => "sg-d1b443b5"
    security_groups.1886755183:                "" => "sg-d9b443bd"
    security_groups.390598185:                 "" => "sg-dab443be"
    security_groups.3985752899:                "" => "sg-b4b443d0"
    security_groups.4086492813:                "" => "sg-6851a20c"
    subnet_id:                                 "" => "subnet-13b90264"
    tags.#:                                    "" => "1"
    tags.Name:                                 "" => "sandbox00"
    tenancy:                                   "" => "<computed>"
    user_data:                                 "" => "467d1edee52cc5a2efa34c135928dd0720d40dd7"

~ aws_route53_record.pph_sandbox
    records.#: "" => "<computed>"

-/+ aws_route53_record.pph_shippable.0
    name:               "<snipped>" => "<snipped>"
    records.#:          "1" => "1"
    records.3586378067: "" => "<snipped>" (forces new resource)
    ttl:                "60" => "60"
    type:               "CNAME" => "CNAME"
    zone_id:            "Z5MJEAK7L5HAZ" => "Z5MJEAK7L5HAZ"
```

The `sandbox` `aws_instance` is added in plan as non-existant thus triggering changes in an `aws_route53_record` and other dependant `aws_elb` entities. And a very weird change on another `aws_route53_record` that makes no sense.

### CODE REVIEW

**Comment by mitchellh** [comment]
Thanks a lot, any way we can get a full debug log here?

**Comment by pmoust** [comment]
@mitchellh thanks for looking into this. I tried removing extra resources out of this while still maintaining the same fault behavior
Here is a link to the log (doesn't fit an a github comment) https://gist.githubusercontent.com/pmoust/cbd23bfa1cbb3b37d03b/raw/terraform_log.txt

**Comment by mitchellh** [comment]
Thanks, is there any way you can share your config/state with me too? If its private and you'd feel comfortable emailing me, then please do that. It'll be hard to debug this without it...

**Comment by mitchellh** [comment]
@pmoust Actually, this diff looks correct to me. What is wrong with it? 

1. Instance gets created
2. ELB instance count is now computed, since you're probably using `${aws_instance.pph_sandbox}` in the instances list.
3. Route53 records are changing since the instance IP is unknown
4. pph_shippable route53 record probably also contains a computed resource from above.

Is that all correct? If so, this diff looks good.

**Comment by pmoust** [comment]
@mitchellh Problem is that `pph_sandbox` instance exists and is already in plan, same goes with `pph_shippable.0` route53 record. Also those entities are not depending on one another.

The ELBs and other route records change due to `pph_sandbox` instance change/creation.

In v0.3.7 I don't face the same issue.

I 'll see if i can add you as a collaborator in a private repo of ours and perhaps supply read only IAM across organization.

**Comment by pmoust** [comment]
@mitchellh I have invited you to our organisation. Sending you IAM credentials in mail.

**Comment by mitchellh** [comment]
@pmoust Thanks, I'll take another look. Note: I don't need _actual_ AWS access so please don't send me any IAM credentials. :) I'd rather not have them at all. I just need the state as Terraform sees it and the configuration. I can run `plan -refresh=false` to reproduce, in theory. 

If you can get me the state file that master generates, that would be ideal.

**Comment by pmoust** [comment]
@mitchellh I 'll send readonly keys, will be revoked shortly after concluding what's up with the issue. Perhaps it's another issue and not graphing. 
State is VCS as well.

**Comment by mitchellh** [comment]
Okay, I've realized something strange about your state file that is causing all of these problems. I am posting this publicly since I won't give away any identifying info you haven't already given out above. 

In your state file there is both an `aws_instance.pph_sandbox` and a `aws_instance.pph_sandbox.0`, as well as the same phenomenon for `aws_route53_record.pph_sandbox`. If you remove the `.0` version of both of those (which appears to come from an older version of Terraform since its missing values from 0.3.7), then the plan is "no changes."

I'm going to look into fixing an issue in TF master to identify this, more info to come.

**Pull request merged**
